### ISSUE TITLE
sha256 of the VIGOR dataset

### ISSUE THREAD

**Issue by ghost** [Jeff-Zilence/VIGOR#10]
Hi, thanks for your excellent work and for providing the relevant dataset. And I noticed that size of the dataset is about 104GB in total, which means that it is quite a large dataset. However, my computer is relatively not that high-performing, which led me to notice a sub-file download error after almost half an hour of unpacking. While my re-download has resolved the issue, it would be helpful if you could agree that posting the SHA256 checksum of the file. It could help someone with the same issue locate and resolve the problem more quickly. Or, If you allow me to, can I post the SHA256 of the corresponding file below this Issue? :)

**Comment by Jeff-Zilence** [comment]
Sure, you can post it. Thanks for sharing.

**Comment by ghost** [comment]
Here's my checksum of the files, I have confirmed that these files can all be extracted and used correctly, and hopefully this will help others to examine the downloaded files more quickly. Thanks again to your excellent work!
![屏幕截图 2023-11-02 170156](https://github.com/Jeff-Zilence/VIGOR/assets/148536311/4e97db61-71ee-4069-8b67-d78ff27a1672)
