### ISSUE TITLE
THE consult of VIGOR

### ISSUE THREAD

**Issue by yangkhkk** [Jeff-Zilence/VIGOR#11]
It is an honor to use the dataset you provided。However,Why did I fill out your questionnaire but did not receive the dataset download method? Could you tell me the specific  download method  of the dataset?

Looking forward to your reply!!

**Comment by Jeff-Zilence** [comment]
You might need to wait for several days before you get the link. I am kind of busy recently. But you should have got the URL now.

**Comment by Miraitowa515** [comment]
I also have been filling out your questionnaire recently, but I have not yet received the download method for the dataset. Could you please take the time to tell me the specific download method for the dataset amidst your busy schedule?

**Comment by Jeff-Zilence** [comment]
You should get the link in several days except:
1) You have submitted multiple questionnaires and we have shared the link previously.
2) You are using the data for commercial use.
3) The provided email is not feasible.

**Comment by Jeff-Zilence** [comment]
Closed if no further questions.
