### ISSUE TITLE
Request for Vigor dataset

### ISSUE THREAD

**Issue by Rodrigues-Royston** [Jeff-Zilence/VIGOR#13]
Dear Authors, 

Thanks for your efforts towards preparing this data-set. 

I have filled the data-set request form & would like to have a link to the data-set for research purposes. 

Thanks and Best Regards,
Royston Rodrigues

**Comment by Jeff-Zilence** [comment]
I think you should have got the link. I will close this issue if there is no further question.

**Comment by Rodrigues-Royston** [comment]
Will be grateful if the link could be sent. 

Currently I wait for response from your team. 

Thanks and Best Regards,
Royston Rodrigues

**Comment by Jeff-Zilence** [comment]
> Will be grateful if the link could be sent.
> 
> Currently I wait for response from your team.
> 
> Thanks and Best Regards, Royston Rodrigues

Can you submit it again? I did not find the request.
