### ISSUE TITLE
The resolution of satellite images

### ISSUE THREAD

**Issue by ssfkfffddj** [Jeff-Zilence/VIGOR#14]
Hello author！I have a question with the VIGOR dataset. You mention in your paper that the satellite images in the VIGOR dataset come from Google Maps with a zoom level of 20 and a resolution of 0.114m, but the level 20 images I found on Google Maps have a resolution of 0.27m. What's the difference here, please?

**Comment by zhouzy-byte** [comment]
Hello, I'm Zhou Ziyang, I want to ask you how to get to jiejue when you can't find the satellite_list.txt path when you can't find the path in the first step。Looking forward to your reply

**Comment by ssfkfffddj** [comment]
啊？I can' understand your question.Could you descript it in more detail?

> Hello, I'm Zhou Ziyang, I want to ask you how to get to jiejue when you can't find the satellite_list.txt path when you can't find the path in the first step。Looking forward to your reply

**Comment by Jeff-Zilence** [comment]
How is the resolution of 0.27m computed? Google Map?

**Comment by ssfkfffddj** [comment]
> How is the resolution of 0.27m computed? Google Map?
Thanks for your reply!
I searched it in the Internet.
https://blog.csdn.net/wdwyf999/article/details/89672780
and
https://blog.csdn.net/luofeixiongsix/article/details/79096089

**Comment by Jeff-Zilence** [comment]
This is a very old blog and there is no way to verify anything it says. Our results are based on scientific fact and you can check other papers for related topics. Closing this if no more question.
