### ISSUE TITLE
VIGOR

### ISSUE THREAD

**Issue by zhouzy-byte** [Jeff-Zilence/VIGOR#15]
Hello author, I am Zhou Ziyang, I have a missing satellite_list.txt error when running code in your VIGOR database, and I found that there is no path I want。Looking forward to your reply

**Comment by Jeff-Zilence** [comment]
Not sure what is the issue here, the file should be in the splits.zip .

**Comment by zhouzy-byte** [comment]
Hello author, I can't find splits.zip, where is the installation package




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jeff-Zilence/VIGOR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jeff-Zilence/VIGOR] VIGOR (Issue #15)





 
Not sure what is the issue here, the file should be in the splits.zip .

**Comment by zhouzy-byte** [comment]
Hello Author, to get the data set is to fill out the questionnaire you prepared in your paper




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Jeff-Zilence/VIGOR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jeff-Zilence/VIGOR] VIGOR (Issue #15)





 
Not sure what is the issue here, the file should be in the splits.zip .
