### ISSUE TITLE
Request for VIGOR dataset

### ISSUE THREAD

**Issue by zhouzy-byte** [Jeff-Zilence/VIGOR#17]
Hello Authors:
  Good evening, thank you for taking the time out of your busy schedule to read my comment..
  I have filled the data-set request form & would like to have a link to the data-set for research .
  Thanks and Best wishes.
  Zhou zi yang

**Comment by Jeff-Zilence** [comment]
We do NOT accept personal email. Please read the questionnaire carefully before you submit it.
