### ISSUE TITLE
question about mining in dataloader.py

### ISSUE THREAD

**Issue by realxuyang** [Jeff-Zilence/VIGOR#5]
hello, line 431 of dataloader.py need self.mining_pool_size >= self.train_sat_data_size, so how to random.sample() a list of n elements from a seq shorter than n? Is this a typo?
![image](https://user-images.githubusercontent.com/45526497/195575275-821e52e6-00e5-445c-88ef-bab11d8faa06.png)

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. The mining_pool_size is smaller than the train_sat_data_size, so we select minig_pool_size samples from a list of length train_sat_data_size. I do not see any problem here. Is there any misunderstanding?

**Comment by Jeff-Zilence** [comment]
I am closing this issue if there is no further question.
