### ISSUE TITLE
How to evaulate your model?

### ISSUE THREAD

**Issue by liguopeng0923** [Jeff-Zilence/VIGOR#7]
Hi,

I want to know how to evaulate models without training (only use the checkpoints to evaluate retrieval accuracy)?

Best wishes.

**Comment by Jeff-Zilence** [comment]
This option is not provided. See the ReadMe page. You can do evaluate from npy. Or directly run the script. It will finish both the training and test.

**Comment by liguopeng0923** [comment]
Ok, thanks.
