### ISSUE TITLE
Question about hyperparameters.

### ISSUE THREAD

**Issue by liguopeng0923** [Jeff-Zilence/VIGOR#9]
Hi,

We want to know the details about the hyperparameter "batch_hard_count" for reproducing the baselines of "SAFA+mining". We also hope you can provide more details about how to set corresponding settings of your  [4 results](https://github.com/Jeff-Zilence/VIGOR/assets/61257834/55a0a1ec-abfa-4467-9aaa-34bd17c8ba2a) in README.md .

Best

**Comment by liguopeng0923** [comment]
Besides, we think "mining strategy" denotes that saving the most 100 dissimilar pairs in "mining_save.npy" before 30 epochs. After 30 epoches, you sample the trained pairs half from the  "mining_save.npy" and half from the original datasets. Please let us know if there is any problem with this understanding.

**Comment by Jeff-Zilence** [comment]
Should be like this. I cannot remember the details right now, but everything should be in the code.

**Comment by liguopeng0923** [comment]
Thanks !
